silius-rs/silius

- .gitmodules
- Cargo.lock
- Cargo.toml
- Makefile
- README.md
- build.rs
- src/contracts/mod.rs
- src/lib.rs
> Generate type safe bindings for abstract accounts (#4)

- Cargo.lock
- Cargo.toml
- src/contracts/entrypoint.rs
- src/contracts/gen.rs
- src/contracts/mod.rs
Introduce a wrapped entry point api that handle the error in our own way.
> Entry point api

- Cargo.lock
- Cargo.toml
- bin/bundler-rpc.rs
- bin/bundler.rs
- src/proto/uopool/uopool.proto
- src/rpc/eth.rs
- src/rpc/eth_api.rs
- src/uopool/mod.rs
- src/uopool/server.rs
- src/uopool/services/uopool.rs
Implementation of `eth_sendUserOperation`.
Next steps are to run sanity checks and simulations in the `uopool` component.
> RPC endpoint eth_sendUserOperation

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- README.md
- src/contracts/entrypoint.rs
- src/utils.rs
- tests/common/mod.rs
- tests/validate_tests.rs
Sadly anvil test node support debug_tracecall with javascript tracer. It would be better to switch to geth dev mode which support javascript tracer.
> Replace anvil with Geth

- .github/workflows/ci.yml
- Makefile
- README.md
CI is now completed in ~5-7 min (prev. 14 min).
> chore: add cache to ci

- src/types/user_operation.rs
- src/uopool/memory_mempool.rs
- src/uopool/memory_reputation.rs
- src/uopool/mod.rs
- tests/common/mod.rs
There is a `RwLock` for mempools and reputations on the UoPoolService level (`Arc<RwLock<HashMap<MempoolId...`), and both will always be accessed over these two hashmaps, thus we don't need async traits for Mempool and Reputation.
> chore: remove async

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/contracts/entrypoint.rs
- src/contracts/tracer.rs
- src/rpc/eth.rs
- src/types/mod.rs
- src/types/sanity_check.rs
- src/types/simulation.rs
- src/types/user_operation.rs
- src/uopool/services/mod.rs
- src/uopool/services/sanity_check.rs
- src/uopool/services/simulation.rs
- src/uopool/services/uopool.rs
- tests/tracer_tests.rs
This adds first checks for simulate validation - forbidden opcodes. It also removes `sanity_check_results` and rertieves the stake info at the start (alongside JS trace).
> First iteration of simulate validation (user operation)

- Cargo.lock
- Cargo.toml
- Makefile
- README.md
- bundler-spec-test/docker-compose.yml
- src/contracts/entrypoint.rs
- tests/validate_tests.rs
@zsluedem Some tests in validate_tests.rs are failing, if you could take a look (maybe it's related to some updates in smart contracts?).
> chore: update deps

- Makefile
- bin/bundler.rs
- src/bundler/mod.rs
- src/proto/uopool/uopool.proto
- src/types/reputation.rs
- src/uopool/database_mempool.rs
- src/uopool/memory_mempool.rs
- src/uopool/mod.rs
- src/uopool/services/uopool.rs
- src/uopool/utils.rs
Enable bundle function in #10 
There is one leftover in the pr.
1. When the user operations are submitted to the client, the bundler needs to observe the transactions are finalized in the blockchain and send a remove request to the pool, and update the reputation accordingly.
Tests are also missing now.
> Send bundles from aa-bundler

- src/contracts/entrypoint.rs
- src/uopool/services/sanity_check.rs
- src/uopool/services/uopool.rs
After upgrading ethers-rs in https://github.com/Vid201/aa-bundler/pull/79.
The JsonRpcError is not reliadble source of revert error because the api changed in ethers-rs.
This pr is intended to remove JsonRpcError struct.
> Remove JsonRpcError

- src/contracts/entrypoint.rs
- src/types/simulation.rs
- src/uopool/services/simulation.rs
- src/uopool/services/uopool.rs
Fix https://github.com/Vid201/aa-bundler/issues/84
Middleware error should be all internal errors which bundler user should not know that. I remove the trait bound on the error type. Be more concrete on the error.
> Fix execution revert case in estimate gas api

- src/res/chainspec/mod.rs
- src/res/mod.rs
@Vid201 Does it make sense to remove this?
> chore: remove unused res folder

- bin/bundler.rs
- src/bundler/mod.rs
- src/proto/uopool/uopool.proto
- src/uopool/services/uopool.rs
This PR does the following:
- implements removing user operations from memool (gRPC)
- skip waiting for transaction receipt - we can add that later, tests are running very long if we wait for receipt (and it's not needed for tests)
- fix some gas issues when sending bundle as tx (tx reverted due to running out of gas)
> chore: remove user operations from mempool

- README.md
- src/bundler/mod.rs
- src/chain/gas.rs
- src/rpc/debug.rs
- src/uopool/database_mempool.rs
- src/uopool/memory_mempool.rs
- src/uopool/mod.rs
- src/uopool/sanity_check.rs
- src/uopool/service.rs
> Replace user operation

- src/proto/types/types.proto
- src/proto/uopool/uopool.proto
- src/rpc/eth.rs
- src/types/user_operation.rs
- src/uopool/mod.rs
- src/uopool/server.rs
- src/uopool/service.rs
- src/uopool/utils.rs
feat add getUserOperationReceipt.
It should be the last piece to pass bundler test spec
> getUserOperationReceipt

- .github/workflows/publish_image.yml
- README.md
- crates/grpc/src/proto.rs
- crates/grpc/src/protos/types/types.proto
- crates/grpc/src/uopool.rs
- crates/uopool/src/canonical/simulation.rs
- crates/uopool/src/utils.rs
This PR fixes bugs that were found during testing with trampoline and candide wallet on Sepolia.
I also changed CI for publishing image so image is build only when something is pushed to main branch.
> Various fixes

- Cargo.lock
- crates/contracts/src/tracer.rs
- crates/uopool/src/canonical/simulation.rs
- tests/Cargo.toml
- tests/src/common/gen.rs
- tests/src/common/mod.rs
- tests/src/validate_tests.rs
https://github.com/Vid201/aa-bundler/issues/66
> Enable validating tests

- .github/workflows/ci.yml
- .gitmodules
- Makefile
- crates/contracts/build.rs
- tests/src/common/gen.rs
Trying to fix this one https://github.com/Vid201/silius/issues/175
> Change building env and thirdparty library for user to build as library

- crates/primitives/src/wallet.rs
- crates/rpc/README.md
- crates/rpc/src/debug.rs
- crates/rpc/src/debug_api.rs
- crates/rpc/src/error.rs
- crates/rpc/src/eth.rs
- crates/rpc/src/eth_api.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/middleware.rs
- crates/rpc/src/rpc.rs
> Rustdoc for crate/rpc crate

- Cargo.lock
- Makefile
- README.md
- bin/silius/src/cli.rs
- bin/silius/src/silius-rpc.rs
- bin/silius/src/silius.rs
- bundler-spec-test/launcher.sh
- crates/rpc/Cargo.toml
- crates/rpc/src/rpc.rs
- crates/rpc/tests/common.rs
- crates/rpc/tests/rpc.rs
- Introduced logic to allow for selectable HTTP and WebSocket endpoints in the json-rpc server.
- Updated CLI arguments to handle `--http` and `--ws` flags for enabling HTTP and WebSocket respectively.
- Modified `JsonRpcServer` instantiation to accept `http` and `ws` boolean flags.
https://github.com/Vid201/silius/issues/155
```sh
> cargo run --release -- --eth-client-address http://127.0.0.1:8545 --mnemonic-file $HOME/.silius/0xabc.. --beneficiary 0xabc.. --entry-points 0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789
...
2023-08-15T09:11:39.502408Z  INFO silius: Starting bundler JSON-RPC server...
2023-08-15T09:11:39.503029Z  INFO silius: Started bundler JSON-RPC server at http://127.0.0.1:8545 with http: true ws: true
> cargo run --release -- --eth-client-address http://127.0.0.1:8545 …
```
> Add support ws RPC API and selectable http and ws api

- crates/uopool/src/utils.rs
The previous implementation had a potential for overflow. The logic has been modified to prevent this issue.
- Removed the use of floating point calculations which might lead to inaccuracies and potential overflows.
- Replaced the previous calculation logic with a more straightforward and safer approach using `saturating_add`, `checked_div`, and other safe arithmetic operations.
- Added tests to ensure the new logic works correctly, especially in scenarios with large user operations and potential overflow situations.
`1. type coversion` in https://github.com/Vid201/silius/issues/191
> Fix `calculate_pre_verification_gas` not to happen overflow problem

- Cargo.lock
- Cargo.toml
- bin/silius/src/bundler.rs
- bin/silius/src/cli/args.rs
- bin/silius/src/cli/commands.rs
- bin/silius/src/utils.rs
- crates/bundler/src/bundler.rs
- crates/contracts/src/entry_point.rs
- crates/grpc/Cargo.toml
- crates/grpc/src/builder.rs
- crates/grpc/src/bundler.rs
- crates/grpc/src/protos/uopool/uopool.proto
- crates/grpc/src/uopool.rs
- crates/primitives/Cargo.toml
- crates/primitives/src/lib.rs
- crates/primitives/src/provider.rs
- crates/rpc/Cargo.toml
- crates/rpc/src/middleware.rs
- crates/uopool/src/memory/mempool.rs
- crates/uopool/src/uopool.rs
- crates/uopool/src/validate/simulation_trace/storage_access.rs
- examples/simple_account/create.rs
- examples/simple_account/deposit.rs
- examples/simple_account/transfer.rs
Bundler now subscribes to new blocks and removes all user operations included on-chain.
> Listen for new blocks and remove user operations

- Cargo.lock
- crates/contracts/Cargo.toml
- crates/contracts/src/entry_point.rs
- crates/uopool/src/uopool.rs
```
res: "{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32603,\"message\":\"Unknown error when simulating validation on entry point. Error message: JsonRpcError(JsonRpcError { code: -32015, message: \\\"VM execution error.\\\", data: Some(String(\\\"Reverted 0x220266b600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000001e41413430206f76657220766572696669636174696f6e4761734c696d69740000\\\")) })\"},\"id\":1}"
```
We could see error message like above in estimateGas. The reverted message could be deserialize to Failop with more concrete message. We should provide that to user with better experience.
> Improve json rpc error message

- bin/silius/src/cli/args.rs
- bin/silius/src/cli/commands.rs
- bin/silius/src/utils.rs
- bundler-spec-tests/launcher.sh
- crates/primitives/src/provider.rs
- examples/storage/examples/database.rs
- examples/storage/examples/memory.rs
add poll interval arg fix #229
> feat: add poll interval arg

- crates/mempool/src/database/mempool.rs
This is a bug which caused people would see not enough stake error when they sent more than 4 userops.
> fix: uo by sender not removed bug

- Cargo.lock
- bin/silius/Cargo.toml
- bin/silius/src/cli/commands.rs
- bin/silius/src/cli/mod.rs
- crates/primitives/src/user_operation/mod.rs
Add a dump database command for debugging
> feat: dump command

- .github/workflows/ci.yml
- README.md
- crates/bundler/src/bundler.rs
- crates/grpc/src/bundler.rs
- crates/mempool/src/validate/mod.rs
- crates/mempool/src/validate/simulation/mod.rs
- crates/mempool/src/validate/simulation/verification_extra_gas.rs
- crates/mempool/src/validate/validator.rs
- crates/primitives/src/constants.rs
- crates/rpc/src/debug.rs
The CI is failing due to old deps and Rust version. Let's merge the p2p PR fist and rebase on this branch.
> chore: update bundler spec tests, update debug send bundle, aa51

- bin/silius/src/bundler.rs
- bin/silius/src/cli/args.rs
- bin/silius/src/utils.rs
- crates/primitives/src/wallet.rs
To load using private key, we can now use the `--private-key` option. And if we want to load with private key using flashbots send bundle mode, we can pass another option `--flashbots-private-key`. An addition option is required for using flashbots mode while loading with private key, since the private key only maps to a single address without hierarchical derivation.
Sample command to load using private key:
`cargo run --release -- node --eth-client-address http://127.0.0.1:8545 --private-key 4c5e5d30… --beneficiary 0xf39Fd6e5… --entry-points 0x5FF137D4… --http --ws`
Sample command to load using private key with flashbots mode:
`cargo run --release -- node --eth-client-address http://127.0.0.1:8545 --private-key 4c5e5d30… --flashbots-private-key df218be...  --send-bundle-mode flashbots …
> feat: support loading private key
